In [22]:
#Work on example of text mining
import numpy as np
import pandas as pd

transcripts=pd.read_csv("C:/Data Analysis/TedTalks/transcripts.csv")
transcripts.head()

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   
2  (Music: "The Sound of Silence," Simon & Garfun...   
3  If you're here today — and I'm very happy that...   
4  About 10 years ago, I took on the task to teac...   

                                                 url  
0  https://www.ted.com/talks/ken_robinson_says_sc...  
1  https://www.ted.com/talks/al_gore_on_averting_...  
2  https://www.ted.com/talks/david_pogue_says_sim...  
3  https://www.ted.com/talks/majora_carter_s_tale...  
4  https://www.ted.com/talks/hans_rosling_shows_t...

In [23]:
transcripts['title']=transcripts['url'].map(lambda x:x.split("/")[-1])
transcripts.head()

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   
2  (Music: "The Sound of Silence," Simon & Garfun...   
3  If you're here today — and I'm very happy that...   
4  About 10 years ago, I took on the task to teac...   

                                                 url  \
0  https://www.ted.com/talks/ken_robinson_says_sc...   
1  https://www.ted.com/talks/al_gore_on_averting_...   
2  https://www.ted.com/talks/david_pogue_says_sim...   
3  https://www.ted.com/talks/majora_carter_s_tale...   
4  https://www.ted.com/talks/hans_rosling_shows_t...   

                                               title  
0        ken_robinson_says_schools_kill_creativity\n  
1               al_gore_on_averting_climate_crisis\n  
2                david_pogue_says_simplicity_sells\n  
3            majora_carter_s_tale_of_urban_renewal\n  
4  hans_rosling_shows_the_best_stats_you_ve_ever_...

In [24]:
from sklearn.feature_extraction import text
Text=transcripts['transcript'].tolist()
tfidf=text.TfidfVectorizer(input=Text,stop_words="english")
matrix=tfidf.fit_transform(Text)
print(matrix.shape)

(2467, 58489)


In [25]:
from sklearn.metrics.pairwise import cosine_similarity
sim_unigram=cosine_similarity(matrix)

print(sim_unigram)

print(sim_unigram.shape)

[[1.         0.15310631 0.17626477 ... 0.07427816 0.1408498  0.06360819]
 [0.15310631 1.         0.16020169 ... 0.03288679 0.11310243 0.06340374]
 [0.17626477 0.16020169 1.         ... 0.06118662 0.14853416 0.05664366]
 ...
 [0.07427816 0.03288679 0.06118662 ... 1.         0.0549175  0.04427896]
 [0.1408498  0.11310243 0.14853416 ... 0.0549175  1.         0.07149283]
 [0.06360819 0.06340374 0.05664366 ... 0.04427896 0.07149283 1.        ]]
(2467, 2467)


In [33]:
def get_similar_articles(x):
    return ",".join(transcripts['title'].loc[x.argsort()[-5:-1]])
transcripts['similar_articles_unigram']=[get_similar_articles(x) for x in sim_unigram]
transcripts['title'].str.replace("_"," ").str.upper().str.strip()[1]


'AL GORE ON AVERTING CLIMATE CRISIS'

In [34]:
transcripts['similar_articles_unigram'].str.replace("_"," ").str.upper().str.strip().str.split("\n")[1]

['RORY BREMNER S ONE MAN WORLD SUMMIT',
 ',ALICE BOWS LARKIN WE RE TOO LATE TO PREVENT CLIMATE CHANGE HERE S HOW WE ADAPT',
 ',TED HALSTEAD A CLIMATE SOLUTION WHERE ALL SIDES CAN WIN',
 ',AL GORE S NEW THINKING ON THE CLIMATE CRISIS']